/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/gltf/scene.gltf 
Author: Drawnah (https://sketchfab.com/EzequielMunoz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmo-bab0bf1991d04757954872507c5b1595
Title: BMO
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { FacePlane } from './FacePlane'

export function BMOModel(props) {
  const { nodes, materials } = useGLTF('/gltf/scene.gltf')
  const modelRef = useRef()
  
  return (
    <group {...props} ref={modelRef} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.895, -0.228, -4.424]} rotation={[-0.602, 0.312, 1.605]} scale={1.401}>
            <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.M_Skate} />
            <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.M_Ruedas} />
            <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.M_Ruedas} />
          </group>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Mat_Atras} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Mat_Atras} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Mat_Atras} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.M_Vidrio} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.M_Piso} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.M_Extremidades} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.M_Extremidades} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.M_Botones} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.M_Cuerpo} />
        </group>
      </group>
      <FacePlane position={[0, 1.2, 0.51]} />
    </group>
  )
}

useGLTF.preload('/gltf/scene.gltf')
